### PR TITLE
deCONZ 6.1.1; Fix VNC on arm & Ledvance downloader

### LINKED ISSUE #1480: deconz 6.1.0 doesnt start on Raspberry Pi 4
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal: line 71: /usr/bin/GCFFlasher_internal.bin: No such file or directory
[16:39:03] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[14:39:04] INFO: Starting udevd...
[14:39:04] INFO: Running the OSRAM LEdvance OTA updater...
[14:39:04] INFO: Running the deCONZ OTA updater...
[services.d] done.
[16:39:04] INFO: Waiting for device...
[14:39:04] INFO: Running the IKEA OTA updater...
[14:39:04] INFO: Can't fetch data from osram!

[16:39:08] INFO: Starting VNC server...
[16:39:11] INFO: Waiting for VNC to start
[16:39:11] INFO: Starting the deCONZ gateway...
./run: line 71: /usr/bin/deCONZ: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

homeassistant/armhf-addon-deconz:6.0.1 

EDIT: FIXED in 6.1.0 - But still not starting - see bugreports below

**Workround:**
For 6.1.0 with the "qt.qpa.screen: QXcbConnection: Could not connect to display :0" Error:

Under Configure, remove the Host Port mapping for 5900/tcp.
After this, VNC will not be started

@pvizeli can you maybe look into this? thx

### PR DESCRIPTION
**Pull request by frenck**
## 6.1.1

- Fix LEDVANCE / OSRAM otau firmware downloader to restart each 65 seconds
- Fix issue with VNC not starting on armhf, armv7 & aarch64 based systems

fixes #1480

### CODE REVIEW

File: deconz/rootfs/etc/services.d/deconz/run [hunk 1]
```diff
@@ -42,11 +42,22 @@ bashio::config.has_value 'dbg_zdp' \
...
 VNC_PORT="$(bashio::addon.port 5900)"
 if bashio::var.has_value "${VNC_PORT}"; then
+    ARCH="$(bashio::info.arch)"
     TMP_FOLDER=$(mktemp -d)
     export XDG_RUNTIME_DIR="${TMP_FOLDER}"
     export DISPLAY=":0"
     PLATFORM="xcb"
 
+    # Fix tigervnc for 32 bits ARM
+    if [[ "armhf aarch64" = *"${ARCH}"* ]]; then
```
Comment (agners) [inline deconz/rootfs/etc/services.d/deconz/run:52]: Shouldn't that read `armhf armv7`?

Comment (frenck) [reply deconz/rootfs/etc/services.d/deconz/run:52]: Well spotted! Thanks

**Comment by agners** [comment]
LGTM
